language: python
python:
    - "2.7"
install:
    - pip install pip --upgrade
    - pip install coverage
    - pip install python-coveralls
    - python setup.py -q install
script:
    - nosetests --with-coverage -v
after_success:
    - coveralls
branches:
    only:
        - master
