language: python
python:
    - 2.7
sudo: false
addons:
    apt:
        packages:
            - pandoc
install:
    - pip install pip --upgrade
    - pip install -r requirements.txt
script:
    - nosetests -v
